# Generated by Django 3.0.5 on 2021-01-30 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Server Name')),
                ('buyPrice', models.FloatField(default=0, verbose_name='Buying Price')),
                ('sellPrice', models.FloatField(default=0, verbose_name='Selling Price')),
                ('serverType', models.CharField(choices=[('MoC', 'Mono-Compte'), ('MuC', 'Multi-Compte'), ('Ret', 'Retro'), ('MoRet', 'Mono-Compte Retro'), ('Tch', 'Touch')], default='Mono-Compte', max_length=255, verbose_name='Server Type')),
                ('stock', models.IntegerField(verbose_name='Kamas Stock')),
            ],
        ),
    ]
