# Generated by Django 3.0.5 on 2021-01-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='name',
            new_name='serverName',
        ),
    ]
